# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '190727_homework_saitama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 190727_homework_saitama

  use_frameworks!
  pod "Koloda"

  pod 'SCLAlertView'

end
